language: python
python:
  - "3.8"
install:
  - pip install -r requirements/base.txt
  - pip install -r requirements/local.txt
services:
  - postgresql
before_script:
  psql -c "create database chess_api_project;" -U postgres
script:
  - make test
  
